"""empty message

Revision ID: 5903c9764e07
Revises: 32c393371493
Create Date: 2022-05-12 15:10:47.581060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5903c9764e07'
down_revision = '32c393371493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('postcode', sa.String(), nullable=True))
    op.add_column('places', sa.Column('toaletaAkt', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('toaletaElektr', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('parking', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('winda', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('brakProgow', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('swobodnyAkt', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('swobodnyElektr', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('drzwiAkt', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('drzwiElektr', sa.Boolean(), nullable=True))
    op.add_column('places', sa.Column('rownyTeren', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_places_lat'), 'places', ['lat'], unique=False)
    op.create_index(op.f('ix_places_lng'), 'places', ['lng'], unique=False)
    op.drop_column('places', 'plus_code')
    op.drop_column('places', 'voivodeship')
    op.drop_column('places', 'accessibility')
    op.drop_column('places', 'postal_code')
    op.add_column('points', sa.Column('lng', sa.Float(), nullable=True))
    op.drop_index('ix_points_long', table_name='points')
    op.create_index(op.f('ix_points_lng'), 'points', ['lng'], unique=False)
    op.drop_column('points', 'plus_code')
    op.drop_column('points', 'active')
    op.drop_column('points', 'long')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('long', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('points', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('points', sa.Column('plus_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_points_lng'), table_name='points')
    op.create_index('ix_points_long', 'points', ['long'], unique=False)
    op.drop_column('points', 'lng')
    op.add_column('places', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('accessibility', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('voivodeship', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('plus_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_places_lng'), table_name='places')
    op.drop_index(op.f('ix_places_lat'), table_name='places')
    op.drop_column('places', 'rownyTeren')
    op.drop_column('places', 'drzwiElektr')
    op.drop_column('places', 'drzwiAkt')
    op.drop_column('places', 'swobodnyElektr')
    op.drop_column('places', 'swobodnyAkt')
    op.drop_column('places', 'brakProgow')
    op.drop_column('places', 'winda')
    op.drop_column('places', 'parking')
    op.drop_column('places', 'toaletaElektr')
    op.drop_column('places', 'toaletaAkt')
    op.drop_column('places', 'postcode')
    op.drop_column('places', 'lng')
    op.drop_column('places', 'lat')
    # ### end Alembic commands ###
